### ISSUE TITLE
Consider publish the theme on ELPA?

### ISSUE THREAD

**Issue by manuel-uberti** [jamescherti/tomorrow-night-deepblue-theme.el#1]
Hi,

first of all thanks for theme. I learnt programming with Turbo Pascal so this brings back a lot of memories. :)

Would you consider publishing the theme on GNU ELPA or Non-GNU ELPA?

**Comment by jamescherti** [comment]
Thank you for the suggestion, @manuel-uberti . Yes, I am considering publishing the theme on GNU ELPA or Non-GNU ELPA.
