### ISSUE TITLE
question/problem with highlight contrast

### ISSUE THREAD

**Issue by BlameTroi** [jamescherti/tomorrow-night-deepblue-theme.el#2]
Beautifully done, but I have a minor problem (it could be my old man eyes).

The contrast when moving through selections (say with fido and M-x) of the highlighted line is almost indistinguishable from the background. I'm not sure how to properly try to change this. The same sort of problem exists if I use visual-hl-mode in code editing. For using the acme theme, I had to do the following to get sufficient contrast with the hl-line and the acme theme:

`(use-package acme-theme
  :config
  (load-theme 'acme t)
  (setopt acme-theme-black-fg t)
  (custom-set-faces
   '(hl-line ((t (
                  :inherit highlight
                  :extend t
                  :background "LightGoldenrod2"
                  :foreground "black"))))
   ))
`
Advice or pointers would be appreciated. I'm not very graphics capable but can experiment if pointed in the right direction.

**Comment by jamescherti** [comment]
Thank you for your kind words and detailed feedback. 

This is how, for example, the Tomorrow Night Deepblue theme looks when using Vertico/Consult:
![image](https://github.com/user-attachments/assets/b7bad7c8-e42b-49ee-8485-fb58e5e7cd0a)

This is how hl-line looks like:
![image](https://github.com/user-attachments/assets/66cac7fc-6156-4f96-b883-600e9539d9d2)

Could you please share a screenshot of how it appears on your screen? That would help me better understand the issue and provide more accurate guidance.

**Comment by BlameTroi** [comment]
Ah, meant to close, so closing now. Thanks again.

**Comment by jamescherti** [comment]
Thank you for confirming that the issue is resolved.
